# Generated by Django 5.0.6 on 2025-04-29 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_localbusiness_tourpackage_guide_culturalexperience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tour_packages/'),
        ),
    ]
