# Generated by Django 5.0.6 on 2025-04-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tourpackage_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tourist',
            old_name='contact_number',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='tourist',
            name='address',
            field=models.TextField(null=True),
        ),
    ]
